project:
  type: website
  output-dir: _site

website:
  title: "iriscc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: installation.qmd
        text: Installation
      - href: d4science.qmd
        text: D4Science
      - href: quickstart.qmd
        text: Quickstart
  sidebar:
    style: "docked"
    contents:
      - section: "Getting started"
        contents:
          - index.qmd
          - installation.qmd
          - d4science.qmd
          - quickstart.qmd
      - section: "Models"
        contents:
          - models/sfincs.qmd
          - models/fiat.qmd
          - models/dhydro.qmd
      - section: "Development"
        contents:
          - developers.qmd

format:
  html:
    theme: cosmo
    toc: true
